USE master
GO
-- CREACION DEL USUARIO A CON PERMISOS DE ADMINISTRADOR
CREATE LOGIN UsuarioA WITH PASSWORD = N'123456'
CREATE USER UsuarioA FOR LOGIN UsuarioA
ALTER SERVER ROLE sysadmin ADD MEMBER UsuarioA


GRANT SELECT, INSERT
ON SCHEMA :: RecursosHumanos
TO Dir_RH
WITH GRANT OPTION 
GO


-- CREAR CON EL USUARIO A LA BASE DE DATOS EMPRESA
CREATE DATABASE EMPRESA
GO

-- CREAR USUARIO B DESDE EL USUARIO A CON PERMISOS DE DDL Y SELECT
USE EMPRESA
GO

CREATE LOGIN UsuarioB WITH PASSWORD = N'abcdef'

CREATE USER UsuarioB FOR LOGIN UsuarioB

ALTER ROLE db_ddladmin ADD MEMBER UsuarioB
GRANT SELECT TO UsuarioB
GRANT EXECUTE TO UsuarioB


-- CREAR USUARIO C DESDE EL USUARIO A CON PERMISOS DE DML Y EXECUTE
CREATE LOGIN UsuarioC WITH PASSWORD = N'24802480'
CREATE USER UsuarioC FOR LOGIN UsuarioC
GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE TO UsuarioC

-- CREAR LA TABLA EMPLEADOS DENTRO DEL ESQUEMA DBO
CREATE TABLE DBO.EMPLEADOS(
	ID_EMPLEADO INT,
	NOMBRE NVARCHAR(50),
	APELLIDOS NVARCHAR(50),
	FECHA_NACIMIENTO DATE,
	SEXO NVARCHAR(1),
	CARGO NVARCHAR(25),
	SALARIO FLOAT
)

--CREACION DE TRIGGERS DESDE EL USUARIO A

--CREAR TABLA LOG
CREATE TABLE DBO.LOG(
	ID INT IDENTITY(1,1),
	INSTRUCCION NVARCHAR(25),
	TABLA_AFECTADA NVARCHAR(25),
	FECHA_ACCION DATETIME
)

--TRIGGER 1

CREATE TRIGGER CONTROL_TABLAS_INSERTAR
ON DEP.DEPARTAMENTO
FOR INSERT
AS
BEGIN
INSERT INTO dbo.LOG (INSTRUCCION, TABLA_AFECTADA, FECHA_ACCION) VALUES('INSERT','DEPARTAMENTO', GETDATE())
END

CREATE TRIGGER CONTROL_TABLAS_ACTUALIZAR
ON DEP.DEPARTAMENTO
FOR UPDATE
AS
BEGIN
INSERT INTO dbo.LOG (INSTRUCCION, TABLA_AFECTADA, FECHA_ACCION) VALUES('UPDATE','DEPARTAMENTO', GETDATE())
END

CREATE TRIGGER CONTROL_TABLAS_ELIMINAR
ON DEP.DEPARTAMENTO
FOR DELETE
AS
BEGIN
INSERT INTO dbo.LOG (INSTRUCCION, TABLA_AFECTADA, FECHA_ACCION) VALUES('INSERT','DEPARTAMENTO', GETDATE())
END


--TRIGGER 2
CREATE TRIGGER CONTROL_TABLAS_INSERTAR_1
ON EMP.EMPLEADO
FOR INSERT
AS
BEGIN
INSERT INTO dbo.LOG (INSTRUCCION, TABLA_AFECTADA, FECHA_ACCION) VALUES('INSERT','EMPLEADO', GETDATE())
END

CREATE TRIGGER CONTROL_TABLAS_ACTUALIZAR_1
ON EMP.EMPLEADO
FOR UPDATE
AS
BEGIN
INSERT INTO dbo.LOG (INSTRUCCION, TABLA_AFECTADA, FECHA_ACCION) VALUES('UPDATE','EMPLEADO', GETDATE())
END

CREATE TRIGGER CONTROL_TABLAS_ELIMINAR_1
ON EMP.EMPLEADO
FOR DELETE
AS
BEGIN
INSERT INTO dbo.LOG (INSTRUCCION, TABLA_AFECTADA, FECHA_ACCION) VALUES('INSERT','EMPLEADO', GETDATE())
END


--TRIGGER 3 Y SP
CREATE PROCEDURE RESPALDO
AS
BEGIN
	IF(OBJECT_ID('EMP.TABLA_EMPLEADO_RESPALDO') IS NOT NULL)
	BEGIN
		DROP TABLE EMP.TABLA_EMPLEADO_RESPALDO
	END

	IF(OBJECT_ID('DEP.TABLA_DEPARTAMENTO_RESPALDO') IS NOT NULL)
	BEGIN
		DROP TABLE DEP.TABLA_DEPARTAMENTO_RESPALDO
	END

	CREATE TABLE EMP.TABLA_EMPLEADO_RESPALDO(
		COD_EMP INT,
		NOMBRE NVARCHAR(50),
		EDAD INT,
		OFICIO NVARCHAR(50),
		DIRECCION NVARCHAR(50),
		FECHA_INGRESO DATE,
		SALARIO INT,
		COMISION INT,
		COD_DEP INT
	)

	CREATE TABLE DEP.TABLA_DEPARTAMENTO_RESPALDO(
		COD_DEP INT,
		NOMBRE_DEP NVARCHAR(50),
		LOCALIZACION NVARCHAR(50)
	)


	SELECT *
	INTO EMP.TABLA_EMPLEADO_RESPALDO
	FROM EMPRESA.EMP.EMPLEADO

	SELECT *
	INTO DEP.TABLA_DEPARTAMENTO_RESPALDO
	FROM EMPRESA.DEP.DEPARTAMENTO
END

-- RESPALDAR TABLA EMP.EMPLEADO
CREATE TRIGGER RESPALDO1
ON EMP.EMPLEADO
FOR INSERT, UPDATE, DELETE
AS
BEGIN
	EXEC RESPALDO_EMPRESA.dbo.RESPALDO
END

-- RESPALDAR TABLA DEP.DEPARTAMENTO
CREATE TRIGGER RESPALDO2
ON DEP.DEPARTAMENTO
FOR INSERT, UPDATE, DELETE
AS
BEGIN
	EXEC RESPALDO_EMPRESA.dbo.RESPALDO
END


CREATE DATABASE RESPALDO_EMPRESA

CREATE SCHEMA EMP

CREATE SCHEMA DEP

CREATE TABLE RESPALDO_EMPRESA.EMP.TABLA_EMPLEADO_RESPALDO(
	COD_EMP INT,
	NOMBRE NVARCHAR(50),
	EDAD INT,
	OFICIO NVARCHAR(50),
	DIRECCION NVARCHAR(50),
	FECHA_INGRESO DATE,
	SALARIO INT,
	COMISION INT,
	COD_DEP INT
)

CREATE TABLE RESPALDO_EMPRESA.DEP.TABLA_DEPARTAMENTO_RESPALDO(
	COD_DEP INT,
	NOMBRE_DEP NVARCHAR(50),
	LOCALIZACION NVARCHAR(50)
)

USE RESPALDO_EMPRESA
GO
CREATE USER UsuarioC FOR LOGIN UsuarioC

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE TO UsuarioC
ALTER ROLE db_ddladmin ADD MEMBER UsuarioC

SELECT * FROM DEP.TABLA_DEPARTAMENTO_RESPALDO
SELECT * FROM EMP.TABLA_EMPLEADO_RESPALDO

DROP PROCEDURE RESPALDO

EXEC COPIA_SEGURIDAD

EXEC MSDB.DBO.sp_send_dbmail
    @profile_name = 'NOTIFICACION_SQL',
    @recipients = 'angel.lopezal@alumno.buap.mx; lopezalvaradoa749@gmail.com',
    @subject = 'Respaldo completado correctamente',
    @body = 'El respaldo se generó de manera correcta.',
	@body_format = 'HTML';
