--INSERCION DE DATOS EN LAS TABLAS DESDE EL USUARIO C
USE EMPRESA
GO
--TABLA EMPLEADOS DEL ESQUEMA DBO
INSERT INTO DBO.EMPLEADOS VALUES(1,'CARLOS','JIMENEZ CLARIN', '1985/05/03','H', 'MOZO', 1500)
INSERT INTO DBO.EMPLEADOS VALUES(2,'ELENA','RUBIO CUESTAS', '1978/09/25','M', 'SECREATRIA', 1300)
INSERT INTO DBO.EMPLEADOS VALUES(3,'JOSÉ','CALVO SISMAN', '1990/11/12','H', 'MOZO', 1400)
INSERT INTO DBO.EMPLEADOS VALUES(4,'MARGARITA','RODRÍGUEZ GARCÉS', '1992/05/16','M', 'SECRETARIA', 1325)

SELECT * FROM DBO.EMPLEADOS
--TABLA DEPARTAMENTO DEL ESQUEMA DEP
INSERT INTO DEP.DEPARTAMENTO VALUES(10, 'DESARROLLO DE SW', 'EL COYOLAR')
INSERT INTO DEP.DEPARTAMENTO VALUES(20, 'ANÁLISIS DE SISTEMAS', 'GUADALUPE')
INSERT INTO DEP.DEPARTAMENTO VALUES(30, 'CONTABILIDAD', 'SUBTIAVA')
INSERT INTO DEP.DEPARTAMENTO VALUES(40, 'VENTAS', 'SAN FELIPE')

SELECT * FROM DEP.DEPARTAMENTO

--TABLA EMPLEADO DEL ESQUEMA EMP
INSERT INTO EMP.EMPLEADO(COD_EMP,NOMBRE,EDAD,OFICIO,DIRECCION,FECHA_INGRESO,SALARIO,COD_DEP) VALUES(1, 'VARGAS HECTOR', 27, 'VENDEDOR', 'LEÓN', '1993/05/12',12000, 40)
INSERT INTO EMP.EMPLEADO VALUES(2, 'HERNANDEZ JULIO', 27, 'ANALISTA', 'CHINANDEGA', '1982/07/14', 13000, 1500, 20)

INSERT INTO EMP.EMPLEADO VALUES(3, 'ESQUIVEL JOSÉ', 31, 'DIRECTOR', 'JUIGALPA', '1981/06/05', 16700, 1200, 30)
INSERT INTO EMP.EMPLEADO(COD_EMP,NOMBRE,EDAD,OFICIO,DIRECCION,FECHA_INGRESO,SALARIO,COD_DEP) VALUES(4, 'DELGADO CARMEN', 37, 'VENDEDOR', 'LEÓN', '1983/03/02',13400, 40)
INSERT INTO EMP.EMPLEADO VALUES(5, 'CASTILLO LUIS', 17, 'VENDEDOR', 'MASAYA', '1982/08/12', 16309, 1000, 40)
INSERT INTO EMP.EMPLEADO(COD_EMP,NOMBRE,EDAD,OFICIO,DIRECCION,FECHA_INGRESO,SALARIO,COD_DEP) VALUES(6, 'ESQUIVEL ALFONSO', 26, 'PRESIDENTE', 'NAGAROTE', '1981/09/12',15000, 30)
INSERT INTO EMP.EMPLEADO(COD_EMP,NOMBRE,EDAD,OFICIO,DIRECCION,FECHA_INGRESO,SALARIO,COD_DEP) VALUES(7, 'PÉREZ LUIS', 32, 'EMPLEADO', 'MANAGUA', '1980/03/02',16890, 10)

SELECT * FROM EMP.EMPLEADO
SELECT * FROM DBO.LOG
TRUNCATE TABLE DBO.LOG

--ACTUALIZAR UN REGISTRO DE LA TABLA DEPARTAMENTO Y EMPLEADO PARA VERIFICAR LA TABLA LOG
UPDATE EMP.EMPLEADO SET COMISION = 1300 WHERE COD_EMP = 1
UPDATE DEP.DEPARTAMENTO SET LOCALIZACION = 'VICTORIA' WHERE COD_DEP = 10

--ACTUALIZAR UN REGISTRO DE LA TABLA DEPARTAMENTO DEL ESQUEMA DEP PARA VERIFICAR EL RESPALDO A LA DB RESPALDO_EMPRESA
UPDATE DEP.DEPARTAMENTO SET LOCALIZACION = 'MARRUECOS' WHERE COD_DEP = 30