USE EMPRESA
-- CREACION DE ESQUEMAS EMP Y DEP POR EL USUARIO B
CREATE SCHEMA EMP

CREATE SCHEMA DEP

CREATE TABLE DEP.DEPARTAMENTO(
	COD_DEP INT,
	NOMBRE_DEP NVARCHAR(50),
	LOCALIZACION NVARCHAR(50)
)

CREATE TABLE EMP.EMPLEADO(
	COD_EMP INT,
	NOMBRE NVARCHAR(50),
	EDAD INT,
	OFICIO NVARCHAR(50),
	DIRECCION NVARCHAR(50),
	FECHA_INGRESO DATE,
	SALARIO INT,
	COMISION INT,
	COD_DEP INT
)

--CREAR UN SP PARA RESPALDAR LA BASE DE DATOS EMPRESA CON EL USUARIO B
ALTER PROCEDURE COPIA_SEGURIDAD
AS
BEGIN
	BACKUP DATABASE EMPRESA
	TO DISK = N'C:\BACKUP_DB_EMPRESA\ARCHIVO1.bak',
	DISK = N'C:\BACKUP_DB_EMPRESA\ARCHIVO2.bak'
END

EXEC COPIA_SEGURIDAD