USE BIBLIOTECA
GO

-- CREACION DEL USUARIO Edgar CON SU RESPECTIVO LOGIN (DESDE AUTENTICACION DE WINDOWS)
CREATE LOGIN Edgar WITH PASSWORD = N'24803900'
CREATE USER Edgar FOR LOGIN Edgar

--ASIGNACION DE PERMISOS DDL, COPIAS DE SEGURIDAD Y EJECUTAR SP´s
ALTER ROLE db_ddladmin ADD MEMBER Edgar
GRANT BACKUP DATABASE, EXECUTE TO Edgar

-- CREACION DEL USUARIO Claudia CON SU RESPECTIVO LOGIN (DESDE AUTENTICACION DE WINDOWS)
CREATE LOGIN Claudia WITH PASSWORD = N'MUFASACAT'
CREATE USER Claudia FOR LOGIN Claudia

--ASIGNACION DE PERMISOS DML
GRANT INSERT, UPDATE, SELECT, DELETE TO Claudia

--INSERCION DE DATOS EN CADA UNA DE LAS TABLAS CON EL USUARIO Claudia
INSERT INTO AUTOR VALUES(1, 'JORGE', 'JUAREZ', 'MARTINEZ', 'MEXICANA')
INSERT INTO AUTOR VALUES(2, 'MANUEL', 'O´LGUIRO', 'MARTINI', 'ITALIANA')

SELECT * FROM AUTOR
TRUNCATE TABLE TELEFONO

INSERT INTO CORREO VALUES(1, 2559801, 'eduardo.lopezju@alumno.buap.mx')
INSERT INTO CORREO VALUES(2, 202054025, 'issac.juarezal@alumno.buap.mx')
SELECT * FROM CORREO

INSERT INTO DEVOLUCION VALUES(1, 2559801, 245800, '2023/09/25')
INSERT INTO DEVOLUCION VALUES(2, 2021578432, 390209, '2023/10/10')
SELECT * FROM DEVOLUCION 

INSERT INTO EDITORIAL VALUES(1, 'ESTELLA')
INSERT INTO EDITORIAL VALUES(2, 'PLANET')
SELECT * FROM EDITORIAL

INSERT INTO ESTUDIANTE VALUES(2559801, 'GERMAN', 'GARMENDIA', 'ESPINOZA', '2003/09/21')
INSERT INTO ESTUDIANTE VALUES(2021578432, 'JUAN', 'HUERTA', 'DOMINGUEZ', '2002/03/12')
SELECT * FROM ESTUDIANTE

INSERT INTO LIBRO VALUES(245800, 'LA CANCION DEL LOBO', 2, 1, '1998/03/15', 'LOBOS Y MANADAS A ELEGIR')
INSERT INTO LIBRO VALUES(2021578432, 'BAJO NOSOTROS', 1, 2, '1990/02/03', 'AMORES DISPERSOS')
SELECT * FROM LIBRO

INSERT INTO PRESTAMO VALUES(1, 2021578432, 1, '2023/09/21')
INSERT INTO PRESTAMO VALUES(2, 245800, 2, '2023/10/12')
SELECT * FROM PRESTAMO

INSERT INTO TELEFONO VALUES(1, 245800, '2213479226')
INSERT INTO TELEFONO VALUES(2, 2021578432, '2211543559')
SELECT * FROM TELEFONO

-- CREAR LAS SIGUIENTES TABLAS CON EL USUARIO Edgar PARA RESPALDAR LAS TABLAS TELEFONO Y AUTOR
CREATE TABLE RESPALDO_TELEFONO(
	ID INT NOT NULL,
	MATRICULA_ESTUDIANTE INT NOT NULL,
	TELEFONO VARCHAR(50)
	CONSTRAINT PK_RESPALDO_TEL PRIMARY KEY (ID)
)

CREATE TABLE RESPALDO_AUTOR(
	ID INT NOT NULL,
	NOMBRE VARCHAR(25),
	APELLIDO_PATERNO VARCHAR(25),
	APELLDIO_MATERNO VARCHAR(25),
	NACIONALIDAD VARCHAR(25)
	CONSTRAINT PK_ID_TEL_RESPALDO PRIMARY KEY (ID)
)

-- CREACION DE TRIGGERS CON EL USUARIO Edgar
CREATE TRIGGER RESPALDO_TABLE_TELEFONO
ON dbo.TELEFONO
AFTER INSERT
AS
BEGIN
	INSERT INTO RESPALDO_TELEFONO (ID, MATRICULA_ESTUDIANTE, TELEFONO)
    SELECT ID, MATRICULA_ESTUDIANTE, TELEFONO
    FROM inserted
	PRINT N'SE COPIÓ CORRECTAMENTE LA INFORMACION A LA TABLA DE RESPALDO'
END


CREATE TRIGGER RESPALDO_TABLA_AUTOR
ON dbo.AUTOR
AFTER INSERT
AS
BEGIN
	INSERT INTO RESPALDO_AUTOR (ID, NOMBRE, APELLIDO_PATERNO, APELLDIO_MATERNO, NACIONALIDAD)
	SELECT ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, NACIONALIDAD
	FROM inserted
	PRINT N'SE COPIÓ CORRECTAMENTE LA INFORMACION A LA TABLA DE RESPALDO'
END

-- MOSTRAR TABLAS DE RESPALDO DESDE EL USUARIO Claudia
INSERT INTO AUTOR VALUES(3, 'DIEGO', 'BENITEZ', 'SUAREZ', 'EUROPEA')
SELECT * FROM RESPALDO_AUTOR

INSERT INTO TELEFONO VALUES(3, 248031020, '2213479226')
SELECT * FROM RESPALDO_TELEFONO

-- RESPALDAR BASE DE DATOS BIBLIOTECA EN DOS ARCHIVOS DESDE EL USUARIO Edgar
BACKUP DATABASE BIBLIOTECA
TO DISK = N'C:/BACKUP_BIBLIOTECA/FILE1.bak',
DISK = N'C:/BACKUP_BIBLIOTECA/FILE2.bak'

-- CONSULTAS QUE EJECUTARÁ EL USUARIO Claudia
SELECT A.NOMBRE, B.ID_LIBRO, B.FECHA_DEVOLUCION
FROM ESTUDIANTE A
INNER JOIN DEVOLUCION B ON B.ID_ESTUDIANTE = A.MATRICULA

SELECT A.NOMBRE EDITORIAL, B.NOMBRE LIBRO, B.FECHA_LANZAMIENTO, B.DESCRIPCION
FROM EDITORIAL A
RIGHT JOIN LIBRO B ON B.ID_EDITORIAL = A.ID

SELECT A. NOMBRE, COUNT(B.ID_AUTOR) NUM_LIBROS
FROM AUTOR A
INNER JOIN LIBRO B ON B.ID_AUTOR = A.ID
GROUP BY A.NOMBRE

-- CREAR SP´s PARA POSTERIORMENTE EJECUTARLO CON UN JOB (TAREA PROGRAMADA)
CREATE PROCEDURE RESPALDO_DB_BIBLIOTECA
AS	
BEGIN
	BACKUP DATABASE BIBLIOTECA
	TO DISK = N'C:/BACKUP_BIBLIOTECA/RESPALDO_MEDIANTE_JOB_BIBLIOTECA.bak'
END

EXEC RESPALDO_DB_BIBLIOTECA -- ESTE CÓDIGO SE EJECUTARÁ EN EL JOB

-- ENVIAR UNA NOTIFICACIÓN A UN CORREO CUANDO LA TAREA PROGRAMADA SE EJECUTE CORRECTAMENTE /(AUTENTICACION WINDOWS)
EXEC MSDB.DBO.sp_send_dbmail
@PROFILE_NAME = 'NOTIFICACION_SQL',
@RECIPIENTS = 'lopezalvaradoa749@gmail.com',
@SUBJECT = 'Backup Database Biblioteca',
@BODY = '<H1 STYLE = "COLOR:DarkGray;">Respaldo ejecutado correctamente</H1>',
@BODY_FORMAT = 'HTML';