--CREATE DATABASE AngelGabrielLopez

USE AngelGabrielLopez
GO

CREATE SCHEMA AGLA

CREATE TABLE AGLA.Datos_Personales(
	ID INT,
	NOMBRE NVARCHAR(50),
	APELLIDO_PATERNO NVARCHAR(50),
	APELLIDO_MATERNO NVARCHAR(50)
)

--LOGIN 1
CREATE LOGIN Angel
WITH PASSWORD = N'1234'

CREATE USER Angel1 FOR LOGIN Angel
WITH DEFAULT_SCHEMA = AGLA

GRANT SELECT, INSERT, UPDATE
ON SCHEMA :: AGLA
TO Angel1
WITH GRANT OPTION

-- LOGIN2

CREATE LOGIN Gabriel
WITH PASSWORD = N'248248'

CREATE USER Gabriel1 FOR LOGIN Gabriel
WITH DEFAULT_SCHEMA = AGLA

GRANT SELECT, INSERT
ON SCHEMA :: AGLA
TO Gabriel1
WITH GRANT OPTION