CREATE DATABASE EJEMPLOS_ARCHIVOS

ON PRIMARY
(
	NAME = 'ARCHIVO_1',
	FILENAME = 'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ARCHIVO_1.mdf',
	SIZE = 5MB,
	MAXSIZE = 10MB,
	FILEGROWTH = 1MB
),
(
	NAME = 'ARCHIVO_2',
	FILENAME = 'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ARCHIVO_2.ndf',
	SIZE = 5MB,
	MAXSIZE = 10MB,
	FILEGROWTH = 1MB
)
LOG ON
(
	NAME = 'ARCHIVO_3',
	FILENAME = 'C:\ARCHIVOS_LOG\ARCHIVO_3.ldf',
	SIZE = 5MB,
	MAXSIZE = 10MB,
	FILEGROWTH = 1MB
),
(
	NAME = 'ARCHIVO_4',
	FILENAME = 'C:\ARCHIVOS_LOG\ARCHIVO_4.ldf',
	SIZE = 5MB,
	MAXSIZE = 10MB,
	FILEGROWTH = 1MB
),
(
	NAME = 'ARCHIVO_5',
	FILENAME = 'C:\ARCHIVOS_LOG\ARCHIVO_5.ldf',
	SIZE = 5MB,
	MAXSIZE = 10MB,
	FILEGROWTH = 1MB
),
(
	NAME = 'ARCHIVO_6',
	FILENAME = 'C:\ARCHIVOS_LOG\ARCHIVO_6.ldf',
	SIZE = 5MB,
	MAXSIZE = 10MB,
	FILEGROWTH = 1MB
)