ALTER TRIGGER RESPALDO 
ON DBO.ALUMNO
FOR INSERT
AS
BEGIN
	IF (object_id('PERSONA_BK') is not null)
	BEGIN 
		DROP TABLE dbo.PERSONA_BK
	END

	CREATE TABLE dbo.PERSONA_BK (
		ID INT,
		MATRI_PROF INT,
		NOMBRE NVARCHAR(50),
		APELLIDO_PAT NVARCHAR(50),
		APELLIDO_MAT NVARCHAR(50),
		CORREO NVARCHAR(50),
		NRC_MATERIA INT
	)

	INSERT INTO dbo.PERSONA_BK
	SELECT * FROM DBO.ALUMNO
END


INSERT INTO ALUMNO VALUES(123, 456, 'ANGELICA', 'RODRIGUEZ', 'VALLEJO','angie2401rova@gmail.com', 87452)

ALTER TABLE ALUMNO DROP CONSTRAINT FK_NR_MAT
ALTER TABLE ALUMNO DROP CONSTRAINT FK_MAT_PROF
ALTER TABLE ALUMNO DROP CONSTRAINT PK_MATRICULA

SELECT * FROM PERSONA_BK


EXEC MSDB.DBO.sp_send_dbmail
@PROFILE_NAME = 'NOTIFICACION_SQL',
@RECIPIENTS = 'angel.lopezal@alumno.buap.mx; angie2401rova@gmail.com; itzelf182@gmail.com',
@SUBJECT = 'NOTIFICACION_PRUEBA',
@BODY = '<H1 STYLE = "COLOR:RED;">ESTA ES UNA PRUEBA DE CORREO</H1>',
@BODY_FORMAT = 'HTML';