CREATE DATABASE PERSONAL

CREATE TABLE EMPELADOS(
ID_EMP INT,
NOMBRE NVARCHAR(50),
APELLIDO1 NVARCHAR(50),
APELLIDO2 NVARCHAR(50),
ID_PUESTO INT,
ID_AREA INT
)

CREATE TABLE PUESTOS(
	ID_PUESTO INT,
	DESCRIPCION NVARCHAR(50)
)

CREATE TABLE AREAS(
ID_AREA INT,
DESCRIPCION NVARCHAR(50)
)


CREATE TRIGGER CONTROL_TABLAS
ON DBO.AREAS
FOR INSERT
AS
BEGIN
INSERT INTO dbo.LOG VALUES(GETDATE(),HOST_NAME(),SUSER_NAME(),'INSERT','AREAS')
END

CREATE TRIGGER CONTROL_TABLAS1
ON DBO.AREAS
FOR UPDATE
AS
BEGIN
INSERT INTO DBO.LOG VALUES(GETDATE(),HOST_NAME(),SUSER_NAME(),'UPDATE','AREAS')
END

CREATE TRIGGER CONTROL_TABLAS2
ON DBO.AREAS
FOR DELETE
AS
BEGIN
INSERT INTO DBO.LOG VALUES(GETDATE(),HOST_NAME(),SUSER_NAME(),'DELETE','AREAS')
END

--TABLA2

CREATE TRIGGER CONTROL_EMPLEADO1
ON DBO.EMPELADOS
FOR INSERT
AS
BEGIN
INSERT INTO DBO.LOG VALUES(GETDATE(),HOST_NAME(),SUSER_NAME(),'INSERT','EMPELADOS')
END

CREATE TRIGGER CONTROL_EMPLEADO2
ON DBO.EMPELADOS
FOR UPDATE
AS
BEGIN
INSERT INTO DBO.LOG VALUES(GETDATE(),HOST_NAME(),SUSER_NAME(),'UPDATE','EMPELADOS')
END

CREATE TRIGGER CONTROL_EMPLEADO3
ON DBO.EMPELADOS
FOR DELETE
AS
BEGIN
INSERT INTO DBO.LOG VALUES(GETDATE(),HOST_NAME(),SUSER_NAME(),'DELETE','EMPELADOS')
END

-- TABLA3
CREATE TRIGGER CONTROL_PUESTO1
ON DBO.PUESTOS
FOR INSERT
AS
BEGIN
INSERT INTO DBO.LOG VALUES(GETDATE(),HOST_NAME(),SUSER_NAME(),'INSERT','PUESTOS')
END

CREATE TRIGGER CONTROL_PUESTO2
ON DBO.PUESTOS
FOR UPDATE
AS
BEGIN
INSERT INTO DBO.LOG VALUES(GETDATE(),HOST_NAME(),SUSER_NAME(),'UPDATE','PUESTOS')
END

CREATE TRIGGER CONTROL_PUESTO3
ON DBO.PUESTOS
FOR DELETE
AS
BEGIN
INSERT INTO DBO.LOG VALUES(GETDATE(),HOST_NAME(),SUSER_NAME(),'DELETE','PUESTOS')
END

-- VALIDACIÓN

INSERT INTO DBO.AREAS VALUES  ('1234','MANTENIMIENTO'), 
('4321','PRODUCCION'),
('5895','MARKETING');

INSERT INTO DBO.EMPELADOS VALUES  (1111,'JUAN','RODRIGUEZ','ALVARADO',5882,5895), 
(2222,'ANA','MARTINEZ','PEREZ',5883,4321), 
(3333,'RAMON','FLORES','RORO',5884,1234);

INSERT INTO DBO.PUESTOS VALUES  (5882,'JEFE'), 
(5883,'SUBJEFE'),
(5884,'GERENTE');

SELECT * FROM DBO.LOG

SELECT * FROM DBO.AREAS
SELECT * FROM DBO.EMPELADOS
SELECT * FROM DBO.PUESTOS

UPDATE AREAS SET ID_AREA = 0000
WHERE ID_AREA = 1234

UPDATE EMPELADOS SET ID_EMP = 5864 
WHERE ID_AREA =1234

UPDATE PUESTOS SET DESCRIPCION = 'JEFE PRINCIPAL'
WHERE ID_PUESTO = 5882

DELETE FROM DBO.AREAS WHERE ID_AREA = 5895
DELETE FROM DBO.EMPELADOS WHERE NOMBRE = 'JUAN'
DELETE FROM DBO.PUESTOS WHERE DESCRIPCION = 'SUBJEFE'

DELETE FROM DBO.EMPELADOS WHERE NOMBRE = ( SELECT TOP 1 NOMBRE FROM DBO.EMPELADOS ORDER BY NOMBRE ASC )
DELETE FROM DBO.PUESTOS WHERE DESCRIPCION = (SELECT TOP 1 DESCRIPCION FROM DBO.PUESTOS ORDER BY DESCRIPCION ASC)