USE model
GO

CREATE TABLE EMPLEADO(
ID INT,
NOMBRE NVARCHAR(50),
APELLIDO_PAT NVARCHAR(50),
APELLIDO_MAT NVARCHAR(50),
FECHA_NAC DATE,
EMAIL_ADDRESS NVARCHAR(50),
CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY (ID)
)

CREATE TABLE PROCESO(
ID INT,
NOMBRE NVARCHAR(50),
GRADO_COMPLEJIDAD NVARCHAR(50),
CONSTRAINT PK_ID_PROCESO PRIMARY KEY (ID)
)

CREATE TABLE PLANTA(
ID INT,
ID_PROCESO INT,
ID_MAQUINA INT,
CONSTRAINT PK_ID_PLANTA PRIMARY KEY(ID),
CONSTRAINT FK_ID_PROCESO FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO(ID)
)

CREATE TABLE MAQUINA(
ID INT,
ID_EMPLEADO INT,
ID_PLANTA INT,
ID_PROCESO INT,
CONSTRAINT PK_ID_MAQUINA PRIMARY KEY (ID),
CONSTRAINT FK_ID_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID),
CONSTRAINT FK_ID_PLANTA FOREIGN KEY (ID_PLANTA) REFERENCES PLANTA(ID),
CONSTRAINT FK_ID_PROCESO_1 FOREIGN KEY (ID_PROCESO) REFERENCES PROCESO(ID)
)

CREATE TABLE TECNICO(
ID_MAQUINA INT,
ID_EMPLEADO INT,
FECHA_SALIDA DATE,
FECHA_REGRESO DATE,
CONDICION_SALIDA NVARCHAR(50),
CONDICION_REGRESO NVARCHAR(50),
CONSTRAINT FK_ID_MAQUINA FOREIGN KEY (ID_MAQUINA) REFERENCES MAQUINA(ID),
CONSTRAINT FK_ID_EMPLEADO_1 FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID),
)

ALTER TABLE PLANTA ADD CONSTRAINT FK_ID_MAQUINA_1 FOREIGN KEY (ID_MAQUINA) REFERENCES MAQUINA(ID)

-- CREACION DE LA BASE DE DATOS
USE master
GO

CREATE DATABASE FAC_PELOTAS
ON PRIMARY
(
	NAME = 'ARCHIVO_MDF',
	FILENAME = 'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ARCHIVO_MDF.mdf',
	SIZE = 10MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 2%
),
FILEGROUP SEGUNDO
(
	NAME = 'ARCHIVO_NDF_1',
	FILENAME = 'C:\ARCHIVOS_NDF\ARCHIVO_NDF_1.ndf',
	SIZE = 10MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 2%
),
FILEGROUP TERCERO
(
	NAME = 'ARCHIVO_NDF_2',
	FILENAME = 'C:\ARCHIVOS_NDF\ARCHIVO_NDF_2.ndf',
	SIZE = 10MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 2%
),
FILEGROUP CUARTO
(
	NAME = 'ARCHIVO_NDF_3',
	FILENAME = 'C:\ARCHIVOS_NDF\ARCHIVO_NDF_3.ndf',
	SIZE = 10MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 2%
),
FILEGROUP QUINTO
(
	NAME = 'ARCHIVO_NDF_4',
	FILENAME = 'C:\ARCHIVOS_NDF\ARCHIVO_NDF_4.ndf',
	SIZE = 10MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 2%
)
LOG ON
(
	NAME = 'ARCHIVO_LOG_1',
	FILENAME = 'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ARCHVIOS_LOG\ARCHIVO_LOG_1.ldf',
	SIZE = 5MB,
	MAXSIZE = 500MB,
	FILEGROWTH = 5MB
),
(
	NAME = 'ARCHIVO_LOG_2',
	FILENAME = 'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ARCHVIOS_LOG\ARCHIVO_LOG_2.ldf',
	SIZE = 5MB,
	MAXSIZE = 500MB,
	FILEGROWTH = 5MB
),
(
	NAME = 'ARCHIVO_LOG_3',
	FILENAME = 'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ARCHVIOS_LOG\ARCHIVO_LOG_3.ldf',
	SIZE = 5MB,
	MAXSIZE = 500MB,
	FILEGROWTH = 5MB
)


ALTER DATABASE FAC_PELOTAS SET RECOVERY SIMPLE
GO

DBCC SHRINKDATABASE(N'FAC_PELOTAS' )
GO