ALTER AUTHORIZATION ON DATABASE::AdventureWorksDW2014 TO sa

USE AdventureWorksDW2014

-- TABLA TEMPORAL 1
SELECT RevisionNumber AS NUMERO_REVISION, 
OrderQuantity AS CANTIDAD_PEDIDO,
UnitPrice AS PRECIO_UNITARIO,
ExtendedAmount AS MONTO_EXTENDIDO,
UnitPriceDiscountPct AS PRECIO_UNITARIO_DESCUENTO,
DiscountAmount AS IMPORTE_DESCUENTO,
ProductStandardCost AS COSTO_PRODUCTO_ESTANDAR,
TotalProductCost AS COSTO_TOTAL_PRODUCTO,
SalesAmount AS IMPORTE_VENTAS,
TaxAmt AS IMPUESTO,
Freight AS TRANSPORTE,
CarrierTrackingNumber AS NUM_SEGUIM_TRANPORTISTA,
CustomerPONumber AS NUMERO_CLIENTE_PO,
OrderDate AS FECHA_PEDIDO,
DueDate AS FECHA_ENTREGA,
ShipDate AS FECHA_ENVIO
INTO #REEVENTAS
FROM dbo.FactResellerSales

SELECT * FROM #REEVENTAS

-- TABLA TEMPORAL 2

SELECT RevisionNumber AS NUMERO_REVISION, 
OrderQuantity AS CANTIDAD_PEDIDO,
UnitPrice AS PRECIO_UNITARIO,
ExtendedAmount AS MONTO_EXTENDIDO,
UnitPriceDiscountPct AS PRECIO_UNITARIO_DESCUENTO,
DiscountAmount AS IMPORTE_DESCUENTO,
ProductStandardCost AS COSTO_PRODUCTO_ESTANDAR,
TotalProductCost AS COSTO_TOTAL_PRODUCTO,
SalesAmount AS IMPORTE_VENTAS,
TaxAmt AS IMPUESTO,
Freight AS TRANSPORTE,
CarrierTrackingNumber AS NUM_SEGUIM_TRANPORTISTA,
CustomerPONumber AS NUMERO_CLIENTE_PO,
OrderDate AS FECHA_PEDIDO,
DueDate AS FECHA_ENTREGA,
ShipDate AS FECHA_ENVIO
INTO #VENTAS_INTERNET
FROM FactInternetSales

SELECT * FROM #VENTAS_INTERNET

-- TABLA TEMPORAL 3

SELECT CurrencyKey AS CLAVE_MONEDA,
DateKey AS CLAVE_FECHA,
AverageRate AS TARIFA_MEDIA,
EndOfDayRate AS TARIFA_FIN_FECHA,
Date AS FECHA
INTO #TIPO_CAMBIO
FROM FactCurrencyRate

SELECT * FROM #TIPO_CAMBIO

-- TABLA FISICA 1
SELECT *
INTO REEVENTAS
FROM #REEVENTAS

--TABLA FISICA 2
SELECT *
INTO VENTAS_INTERNET
FROM #VENTAS_INTERNET

--TABLA FISICA 3
SELECT *
INTO TIPO_CAMBIO
FROM #TIPO_CAMBIO

-- BACKUP's

BACKUP DATABASE AdventureWorksDW2014
TO DISK = 'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\Backup\AdventuresWorksDW_1.bak'
--DISK = 'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\Backup\AdventuresWorksDW_1.bak'

BACKUP DATABASE AdventureWorksDW2014
TO DISK = 'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\Backup\AdventuresWorksDW_2.bak'


-- PAGINAS QUE TIENEN LAS TABLAS CREADAS
SELECT
	OBJECT_NAME(OBJECT_ID) AS TABLAS_NUEVAS,
	SUM(RESERVED_PAGE_COUNT) AS PAGINAS_RESERVADAS,
	SUM(used_page_count) AS PAGINAS_USADAS
FROM sys.dm_db_partition_stats
WHERE OBJECT_NAME(OBJECT_ID) IN ('REEVENTAS','VENTAS_INTERNET','TIPO_CAMBIO')
GROUP BY OBJECT_ID

-- PAGINAS QUE TIENEN LAS TABLAS ORIGINALES
SELECT
	OBJECT_NAME(OBJECT_ID) AS TABLAS_ORIGINALES,
	SUM(RESERVED_PAGE_COUNT) AS PAGINAS_RESERVADAS,
	SUM(used_page_count) AS PAGINAS_USADAS
FROM sys.dm_db_partition_stats
WHERE OBJECT_NAME(OBJECT_ID) IN ('FactResellerSales','FactInternetSales','FactCurrencyRate')
GROUP BY OBJECT_ID
