CREATE DATABASE GABINETE_ABOGADOS

USE GABINETE_ABOGADOS

CREATE TABLE ASUNTO
(
	ID INT,
	ID_ABOGADO INT,
	ID_CLIENTE INT,
	ID_ESTADO INT,
	FECHA_INICIO NVARCHAR(50),
	FECHA_FIN NVARCHAR(50),
	CONSTRAINT PK_ID PRIMARY KEY (ID)
)

ALTER TABLE ASUNTO ADD CONSTRAINT FK_ID FOREIGN KEY (ID_ABOGADO) REFERENCES ABOGADO(ID)
ALTER TABLE ASUNTO ADD CONSTRAINT FK_ID_1 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
ALTER TABLE ASUNTO ADD CONSTRAINT FK_ID_2 FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID)

CREATE TABLE CLIENTE
(
	ID INT,
	ID_ASUNTO INT,
	NOMBRE NVARCHAR(50),
	APELLIDO_PAT NVARCHAR(50),
	APELLIDO_MAT NVARCHAR(50),
	DIRECCION TEXT,
	CONSTRAINT PK_ID_1 PRIMARY KEY (ID)
)

ALTER TABLE CLIENTE ADD CONSTRAINT FK_ID_3 FOREIGN KEY (ID_ASUNTO) REFERENCES ASUNTO(ID)

CREATE TABLE ABOGADO
(
	ID INT,
	ID_ASUNTO INT,
	NOMBRE NVARCHAR(50),
	APELLIDO_PAT NVARCHAR(50),
	APELLIDO_MAT NVARCHAR(50),
	ESPECIALIDAD NVARCHAR(50),
	CONSTRAINT PK_ID_2 PRIMARY KEY (ID)
)

ALTER TABLE ABOGADO ADD CONSTRAINT FK_ID_4 FOREIGN KEY (ID_ASUNTO) REFERENCES ASUNTO(ID)

CREATE TABLE ESTADO
(
	ID INT,
	ESTADO NVARCHAR(50),
	CONSTRAINT PK_ID_3 PRIMARY KEY (ID)
)